name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: mypy
      run: |
        mypy --ignore-missing-imports --disallow-untyped-defs --disallow-incomplete-defs --disallow-subclassing-any --disallow-any-generics --no-implicit-optional --warn-redundant-casts --warn-unused-ignores --warn-unreachable --allow-untyped-decorators .
    - name: flake8
      run: |
        flake8 .
    - name: pytest
      run: |
        pytest .
